#define VGA_MEMORY_ADDRESS	0xB8000
#define VGA_WIDTH 	80
#define VGA_HEIGHT 	25

#define VGA_CRTC_ADDRESS	0x3D4
#define VGA_CRTC_DATA		0x3D5

#define VGA_REG_CURSOR_START	0x0A
#define VGA_REG_CURSOR_END		0x0B
#define VGA_REG_CURSOR_LOC_HIGH	0x0E
#define VGA_REG_CURSOR_LOC_LOW	0x0F

#define VGA_CURSOR_DISABLE			0x20
#define VGA_CURSOR_SCANLINE_START	0x0
#define VGA_CURSOR_SCANLINE_END		0xF

#define MONO_BASE	0x3B4
#define MONO_BUF	0xB0000
#define CGA_BASE	0x3D4
#define CGA_BUF		0xB8000

#define VGA_BUF 0xA0000

typedef enum {
	VGA_COLOR_BLACK = 0,
	VGA_COLOR_BLUE = 1,
	VGA_COLOR_GREEN = 2,
	VGA_COLOR_CYAN = 3,
	VGA_COLOR_RED = 4,
	VGA_COLOR_MAGENTA = 5,
	VGA_COLOR_BROWN = 6,
	VGA_COLOR_LIGHT_GREY = 7,
	VGA_COLOR_DARK_GREY = 8,
	VGA_COLOR_LIGHT_BLUE = 9,
	VGA_COLOR_LIGHT_GREEN = 10,
	VGA_COLOR_LIGHT_CYAN = 11,
	VGA_COLOR_LIGHT_RED = 12,
	VGA_COLOR_LIGHT_MAGENTA = 13,
	VGA_COLOR_LIGHT_BROWN = 14,
	VGA_COLOR_WHITE = 15,
} vga_color_t;